### ISSUE TITLE
User.score! returns true

### ISSUE THREAD

**Issue by benjaminhouy** [jaysonvirissimo/active_recall#29]
Hi,

There seems to be an issue with the score! method in 

Running the following:

`User.first.score!(1, Phrase.first)`

Leads to the following error:

```
eval error: undefined method `score' for true
  /Users/bhouy/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/active_recall-2.0.1/lib/active_recall/models/item.rb:24:in `score!'
  /Users/bhouy/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/active_recall-2.0.1/lib/active_recall/item_methods.rb:14:in `score!'

```

I believe the issue is that update! returns true, so score is ran on a boolean:

```
if algorithm_class.type == :gradable
        update!(
          algorithm_class.score(**scoring_attributes.merge(grade: grade))
        ).score
```

**Comment by jaysonvirissimo** [comment]
Thanks for reporting that @benjaminhouy. LMK if SM-2 works in version `2.0.2`. 👍🏼

**Comment by benjaminhouy** [comment]
Thanks for the update Jayson but now I get the following:

missing keyword: :easiness_factor

[active_recall (2.0.2) lib/active_recall/algorithms/sm2.rb:11:in `score']
[active_recall (2.0.2) lib/active_recall/models/item.rb:23:in `score!']
[active_recall (2.0.2) lib/active_recall/item_methods.rb:14:in `score!']
[app/controllers/phrases_controller.rb:143:in `guess']

**Comment by jaysonvirissimo** [comment]
@benjaminhouy that most likely indicates the schema migration that added the `:easiness_factor` column hasn't been run yet. You may need to `rails generate active_recall` again to get that migration added and then `rails db:migrate` to get your database set up properly.
